include-y+=httpserver/httpserver.h
include-$(LIBURI)+=httpserver/uri.h
include-$(LIBUTILS)+=httpserver/utils.h
include-$(LIBWEBSOCKET)+=httpserver/websocket.h
include-$(WEBSOCKET)+=httpserver/mod_websocket.h
include-$(MBEDTLS)+=httpserver/mod_tls.h
include-$(COOKIE)+=httpserver/mod_cookie.h
